pm2 scripts: minor fixes (waiting for the big rewriting)
git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@20079 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/bin/pm2-flavor b/bin/pm2-flavor
--- a/bin/pm2-flavor
+++ b/bin/pm2-flavor
@@ -218,7 +218,7 @@ set_option() { # option max_val filtre null_allowed
 	if [ ! -z "$3" ]; then
 	    optverif="${optarg//[^$3]}"
 	    if [ "$optverif" != "$optarg" ]; then
-		echo "Invalid caracters in parameter --$optname : $optarg" 1>&2
+		echo "Invalid characters in parameter --$optname : $optarg" 1>&2
 		exit 1
 	    fi
 	fi
