use variable _PM2_WHICH_PROGNAME to display program name
git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@18669 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/bin/pm2-which b/bin/pm2-which
--- a/bin/pm2-which
+++ b/bin/pm2-which
@@ -234,7 +234,7 @@ shift
 pm2_which_calc "$_PM2_WHICH_PROG"
 if [ $_PM2_WHICH_SOURCE_MODE = no ]; then
     if [ -z "$_PM2_WHICH_NB_FOUND" ] || [ $_PM2_WHICH_NB_FOUND -eq 0 ] ; then
-        echo "pm2_which: '${_PROG}' exec file not found" 1>&2
+        echo "$_PM2_WHICH_PROGNAME: '${_PROG}' exec file not found" 1>&2
     else
         pm2_which_prettyprint $_PM2_WHICH_RESULT
     fi
@@ -245,10 +245,10 @@ if [ $_PM2_WHICH_SOURCE_MODE = no ]; then
     fi
 else
     if [ -z "$_PM2_WHICH_NB_FOUND" ] || [ $_PM2_WHICH_NB_FOUND -eq 0 ] ; then
-        pm2_which_error "pm2_which: '${_PROG}' exec file not found"
+        pm2_which_error "$_PM2_WHICH_PROGNAME: '${_PROG}' exec file not found"
     fi
     if [ -z "$_PM2_WHICH_NB_FOUND" ] || [ $_PM2_WHICH_NB_FOUND -gt 1 ] ; then
-        pm2_which_error "pm2_which: multiple ${_PROG} example binaries found"
+        pm2_which_error "$_PM2_WHICH_PROGNAME: multiple ${_PROG} example binaries found"
     fi
 fi
 
