pm2-test: print the number of performed tests, of passes and of failures. No longer congratulates when no tests have been performed
git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@21731 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/bin/pm2-test b/bin/pm2-test
--- a/bin/pm2-test
+++ b/bin/pm2-test
@@ -177,6 +177,7 @@ do_the_test()
         fi
 	if [ `cat $file_status` -ne 0 ] ; then
 	    failures_per_module="$failures_per_module $prog (flavor $flavor)"
+	    nb_failures_per_module=`expr $nb_failures_per_module + 1`
 	    pm2_test_warning_file "Execution of $prog failed: return value is not 0" $file_result
 	    return 1
 	fi
@@ -203,8 +204,10 @@ do_the_test()
         grep -v '^#' $file_result | grep -v Puk: | grep -v PadicoTM | grep -v ".ssh.rc" | grep -v "X11 forwarding" | grep -v xauth | $sort_command | $head_command > $file_filtered
         if diff -u $file_expected $file_filtered ; then
 	    echo "Test ok!"
+	    nb_passes_per_module=`expr $nb_passes_per_module + 1`
         else
 	    failures_per_module="$failures_per_module $prog (flavor $flavor)"
+	    nb_failures_per_module=`expr $nb_failures_per_module + 1`
 	    pm2_test_warning_file "Test $prog failed: unexpected result (see $file_result)" $file_filtered
 	    return 1
         fi
@@ -393,13 +396,22 @@ fi
 _to_test="$_prefix $_suffix"
 
 failures=""
+nb_tests=0
+nb_passes=0
+nb_failures=0
 _l=$_init_level
 while [ $_l -le $_level ]; do
     failures_per_level=""
+    nb_tests_per_level=0
+    nb_passes_per_level=0
+    nb_failures_per_level=0
 
     for _m in $_to_test ; do
 	echo "*** Testing module $_m ***"
 	failures_per_module=""
+	nb_tests_per_module=0
+	nb_failures_per_module=0
+	nb_passes_per_module=0
 
         shopt -u nullglob
 	cd ${PM2_ROOT}/modules/$_m/test
@@ -447,108 +459,118 @@ while [ $_l -le $_level ]; do
 		    appdir2=$(echo $appdir | tr '/' ':')
 		    echo $prog $_f >> /tmp/tests_${USER}_database/${flavor}.${appdir2}.dat
 		    echo $_f >> /tmp/tests_${USER}_database/${flavor}.flavor
+		    nb_tests_per_module=`expr $nb_tests_per_module + 1`
                 fi
             done
 
-	    echo "*** Compiling flavor for level $_l tests ***"
-	    shopt -s nullglob
-	    for f in /tmp/tests_${USER}_database/*.flavor ; do
-		d_flavor=$(basename $f .flavor)
+	    if [ $nb_tests_per_module == 0 ] ; then
+		echo "*** No tests to be performed for module $_m and level $_l ***"
+	    else
+		echo "*** Compiling flavors and performing tests for level $_l ***"
+		shopt -s nullglob
+		for f in /tmp/tests_${USER}_database/*.flavor ; do
+		    d_flavor=$(basename $f .flavor)
 
-		CC=${CC:-$(pm2-config --flavor=$d_flavor --cc)}
-		file_status="/tmp/pm2test_${USER}_status"
+		    CC=${CC:-$(pm2-config --flavor=$d_flavor --cc)}
+		    file_status="/tmp/pm2test_${USER}_status"
 
-		echo "Compiling flavor <$d_flavor>..."
-		(CPPFLAGS="$CPPFLAGS" LDFLAGS="$LDFLAGS" ${PM2_MAKE:-make} CC="$CC" FLAVOR=$d_flavor PM2_FLAVOR=$d_flavor $jobs -C $PM2_ROOT $jobs; echo "$?" > $file_status ) | sed -e 's/^/..../'
+		    echo "*** Compiling flavor <$d_flavor>..."
+		    (CPPFLAGS="$CPPFLAGS" LDFLAGS="$LDFLAGS" ${PM2_MAKE:-make} CC="$CC" FLAVOR=$d_flavor PM2_FLAVOR=$d_flavor $jobs -C $PM2_ROOT $jobs; echo "$?" > $file_status ) | sed -e 's/^/..../'
 
-		if [ `cat $file_status` -ne 0 ] ; then
-		    pm2_test_warning "Compilation of the flavor $d_flavor failed."
-		fi
-
-		echo "Compiling and performing tests for flavor <$d_flavor>"
-		for _t in $(cat $f) ; do
-		    _tst_name="`pm2_test_name $_t`"
-		    echo "Level [$_l], module [$_m], Test [$_tst_name]"
-
-		    # by default, do not sort the output
-		    sort_output=0
-
-		    alias pm2_skip_test='{ echo "Skipping level [$_l], module [$_m], Test [$_tst_name]" ; continue; }'
-
-	            # Source
-		    . ./$_t
-
-		    (CPPFLAGS="$CPPFLAGS" LDFLAGS="$LDFLAGS" ${PM2_MAKE:-make} CC="$CC" $jobs -C $appdir $prog FLAVOR=$flavor PM2_FLAVOR=$flavor; echo "$?" > $file_status) | sed -e 's/^/..../'
-		    [ `cat $file_status` -eq 0 ] || pm2_test_warning "Compilation of the application <$prog> failed"
-
-		    # Execution et verification des resultats
-		    if eval do_the_test "$_t" $_output_redirect; then
-			echo "   [$_tst_name] did succeed."
-		    else
-			echo "   [$_tst_name] did fail."
+		    if [ `cat $file_status` -ne 0 ] ; then
+			pm2_test_warning "Compilation of the flavor $d_flavor failed."
 		    fi
-		done
 
-		if [ "$_coverage" = "yes" ] ; then
-		    # Enumerate all the lcov-generated `.info' files.
-		    lcov_options=""
-                    gcov_dirs=$(find $(pm2-config --flavor=$flavor --builddir) -name coverage -type d)
-		    for gcov_dir in $gcov_dirs/* ; do
-			if [ -d "$gcov_dir" ] ; then
-			    for file in "$gcov_dir"/*.info ; do
-				if [ -s "$file" ] ; then
-				    lcov_options="$lcov_options -a $file"
-				fi
-			    done
+		    echo "*** Compiling and performing tests for flavor <$d_flavor>"
+		    for _t in $(cat $f) ; do
+			_tst_name="`pm2_test_name $_t`"
+			echo "*** Level [$_l], module [$_m], Test [$_tst_name]"
+
+			# by default, do not sort the output
+			sort_output=0
+
+			alias pm2_skip_test='{ echo "Skipping level [$_l], module [$_m], Test [$_tst_name]" ; continue; }'
+
+			# Source
+			. ./$_t
+
+			(CPPFLAGS="$CPPFLAGS" LDFLAGS="$LDFLAGS" ${PM2_MAKE:-make} CC="$CC" $jobs -C $appdir $prog FLAVOR=$flavor PM2_FLAVOR=$flavor; echo "$?" > $file_status) | sed -e 's/^/..../'
+			[ `cat $file_status` -eq 0 ] || pm2_test_warning "Compilation of the application <$prog> failed"
+
+			# Execution et verification des resultats
+			if eval do_the_test "$_t" $_output_redirect; then
+			    echo "   [$_tst_name] did succeed."
+			else
+			    echo "   [$_tst_name] did fail."
 			fi
 		    done
 
-		    lcov_html_report_dir="$(dirname $(pm2-config --flavor=$flavor --builddir))/coverage/$_m"
-		    rm -rf "$lcov_html_report_dir"
-		    mkdir -p "$lcov_html_report_dir"
+		    if [ "$_coverage" = "yes" ] ; then
+			# Enumerate all the lcov-generated `.info' files.
+			lcov_options=""
+			gcov_dirs=$(find $(pm2-config --flavor=$flavor --builddir) -name coverage -type d)
+			for gcov_dir in $gcov_dirs/* ; do
+			    if [ -d "$gcov_dir" ] ; then
+				for file in "$gcov_dir"/*.info ; do
+				    if [ -s "$file" ] ; then
+					lcov_options="$lcov_options -a $file"
+				    fi
+				done
+			    fi
+			done
 
-		    # Aggregate all the lcov-generated `.info' files.
-		    lcov_global_info_file="$lcov_html_report_dir/${_m}.info"
-		    lcov $lcov_options > "$lcov_global_info_file"
+			lcov_html_report_dir="$(dirname $(pm2-config --flavor=$flavor --builddir))/coverage/$_m"
+			rm -rf "$lcov_html_report_dir"
+			mkdir -p "$lcov_html_report_dir"
 
-		    # Generate the HTML report.
-		    echo "generating HTML coverage report under \`$lcov_html_report_dir'..."
-		    genhtml -o "$lcov_html_report_dir" "$lcov_global_info_file" && \
-			echo "HTML coverage report available under \`$lcov_html_report_dir'..."
-		fi
+			# Aggregate all the lcov-generated `.info' files.
+			lcov_global_info_file="$lcov_html_report_dir/${_m}.info"
+			lcov $lcov_options > "$lcov_global_info_file"
 
-	    done
+			# Generate the HTML report.
+			echo "generating HTML coverage report under \`$lcov_html_report_dir'..."
+			genhtml -o "$lcov_html_report_dir" "$lcov_global_info_file" && \
+			    echo "HTML coverage report available under \`$lcov_html_report_dir'..."
+		    fi
 
-	    if [ -z "$failures_per_module" ] ; then
+		done
+	    fi
+
+	    if [ $nb_tests_per_module == 0 ] ; then
+		echo ">>> Level [$_l] tests for module [$_m] : all tests have been skipped"
+	    elif [ -z "$failures_per_module" ] ; then
 		echo ">>> Level [$_l] tests for module [$_m] did succeed!"
 	    else
 		echo ">>> Some of the level [$_l] tests for module [$_m] did fail: $failures_per_module"
 		failures_per_level="$failures_per_level [Module $_m: $failures_per_module]"
 	    fi
+	    nb_tests_per_level=`expr $nb_tests_per_level + $nb_tests_per_module`
+	    nb_passes_per_level=`expr $nb_passes_per_level + $nb_passes_per_module`
+	    nb_failures_per_level=`expr $nb_failures_per_level + $nb_failures_per_module`
 	fi
     done
 
-    if [ -z "$failures_per_level" ] ; then
+    if [ $nb_tests_per_level == 0 ] ; then
+	echo ">>>>>> Results for Level [$_l]: all tests have been skipped!"
+    elif [ -z "$failures_per_level" ] ; then
 	echo ">>>>>> Results for Level [$_l]: all tests have succeeded!"
     else
 	echo ">>>>>> Results for Level [$_l]: some tests have failed: $failures_per_level"
 	failures="$failures [Level $_l: $failures_per_level]"
     fi
-
+    nb_tests=`expr $nb_tests + $nb_tests_per_level`
+    nb_passes=`expr $nb_passes + $nb_passes_per_level`
+    nb_failures=`expr $nb_failures + $nb_failures_per_level`
     _l=`expr $_l + 1`
 done
 
 echo
-if [ -z "$failures" ] ; then
-    # ########## Happy end ##########
-    echo "         ************************"
-    echo "         *** Congratulations! ***"
-    echo "         ************************"
-else
-    echo "         ****************************"
-    echo "         *** Go and fix your code ***"
-    echo "         ****************************"
-    echo
+echo "# of passes		$nb_passes"
+echo "# of failures		$nb_failures"
+echo "# of performed tests	$nb_tests"
+
+if [ -n "$failures" ] ; then
+    echo ""
     echo "Failures: $failures"
 fi
 exit 0
