rev 1.2 at 2001/01/11 10:45:51 GMT  pm2-fast-config becomes pm2-config (the old one was removed)
(Logical change 1.386)


git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@4148 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/pm2/pm2/bin/ezflavor b/pm2/pm2/bin/ezflavor
--- a/pm2/pm2/bin/ezflavor
+++ b/pm2/pm2/bin/ezflavor
@@ -46,4 +46,11 @@ case "$PM2_SYS" in
 	;;
 esac
 
+prog=${PM2_HOME:-${HOME}}/.pm2/bin/ezflavor_${PM2_ARCH}_${PM2_SYS}${ext}
+
+if [ ! -x $prog ]; then
+    echo "ERROR: ezflavor was not compiled for $PM2_ARCH/$PM2_SYS" >&2
+    exit 1
+fi
+
 exec ${PM2_HOME:-${HOME}}/.pm2/bin/ezflavor_${PM2_ARCH}_${PM2_SYS}${ext} "$@"
