rev 1.3 at 2000/11/03 16:20:37 GMT  Nothing important.
2003/09/05 06:04:21+02:00 ens-lyon.fr!gantoniu
rev 1.2 at 2000/11/03 14:08:09 GMT
 Updated pm2-update-fut and pm2prof to take into account the recent fut files added by Bob and the new switches of fut_print.

(Logical change 1.346)


git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@3716 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/pm2/pm2/bin/pm2-update-fut b/pm2/pm2/bin/pm2-update-fut
--- a/pm2/pm2/bin/pm2-update-fut
+++ b/pm2/pm2/bin/pm2-update-fut
@@ -1,21 +1,49 @@
-#!/bin/sh
+#!/bin/sh 
 
-FUTD=${HOME}/devel/fut
+PROGNAME=pm2-update-fut
+
+
+error() # msg
+{
+    echo $*
+    exit 1
+}
+
+
+usage() # exit_code
+{
+    echo "Usage: $PROGNAME <source directory>"
+    exit $1
+}
+
+
+[ $# -eq 1 ] || usage 1
+
+FUTD=$1
+
+[ -d $1 ] || error "Error: $1 is not a valid directory"
+
 PROFD=${PM2_ROOT}/profile
 
 copy()
 {
+ if [ -f $1 ]; then
     cp $1 $2
     chmod a+r $2/`basename $1`
     echo "File `basename $1` updated"
+ else
+    echo "Warning: $1 : file not found"
+ fi
 }
 
 # Include
 copy ${FUTD}/fut.h ${PROFD}/include
+copy ${FUTD}/get_cpu_mhz.h ${PROFD}/include
 
 # Source
 copy ${FUTD}/fut_header.S ${PROFD}/source
 copy ${FUTD}/fut_setup.c ${PROFD}/source
+copy ${FUTD}/get_cpu_mhz.c ${PROFD}/source
 
 # Bin/src
 copy ${FUTD}/fut_print.c ${PROFD}/bin/src
