rev 1.7 at 2000/05/25 00:23:36 GMT  marcel_poll with sisci and few bugs fixes
(Logical change 1.197)


git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@2391 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/pm2/pm2/bin/pm2-flavor b/pm2/pm2/bin/pm2-flavor
--- a/pm2/pm2/bin/pm2-flavor
+++ b/pm2/pm2/bin/pm2-flavor
@@ -45,6 +45,7 @@ SETTINGS='### SETTINGS:'
 
 PM2_MODULE="${PM2_ROOT}/bin/pm2-module"
 PM2_CONFIGPROG="${PM2_ROOT}/bin/pm2-config"
+PM2_FLAVOR="${PM2_ROOT}/bin/pm2-flavor"
 
 MODULES=`"${PM2_ROOT}/bin/pm2-module" modules --with-common`
 
@@ -75,8 +76,10 @@ Commands
   list      : list existing flavors
   get       : print a command line that can be used to generate the flavor
   help      : this help
-  help cmd  : help on command 'cmd'
   check     : check correctness
+  regenerate: regenerate the flavor
+
+  => use "$PROGNAME help cmd" to get help on command 'cmd'
 
 EOF
 
@@ -162,6 +165,13 @@ Modules configurated are:
 
 EOF
 	;;
+    regenerate)
+	cat <<EOF
+Options for '$2' command 
+  --flavor=""      name of the flavor to regenerate (default : all flavors)
+
+EOF
+	;;
     *)
 	cat <<EOF
 Command '$2' unknown
@@ -229,6 +239,8 @@ set_option() { # option max_val filtre null_allowed
 create_flavor() {
     $ECHO "Creating flavor '$flavor'"
     OUT="${PM2_CONFIG}/$flavor"
+    OUTOLD="${PM2_CONFIG}/$flavor.old"
+    test -f "$OUT" && mv "${OUT}" "${OUTOLD}"
     echo "# Flavor $flavor" > ${OUT} || exit 1
     echo "${SETTINGS} --flavor=$flavor" >> ${OUT}
     echo "${SETTINGS} --builddir=$builddir" >> ${OUT}
@@ -270,9 +282,21 @@ create_flavor() {
 	    done
 	fi
     done
-    
-    mkdir -p "${PM2_ROOT}/stamp${builddir:+/$builddir}"
-    echo $flavor > "${PM2_ROOT}/stamp${builddir:+/$builddir}/stamp$ext"
+
+    if diff "${OUTOLD}" "${OUT}" >/dev/null 2>&1; then
+	echo "flavor '$flavor' unmodified"
+    else
+	echo "$1"
+	mkdir -p "${PM2_ROOT}/stamp${builddir:+/$builddir}"
+	echo $flavor > "${PM2_ROOT}/stamp${builddir:+/$builddir}/stamp$ext"
+    fi
+    rm -f "${OUTOLD}" 2>/dev/null
+    if [ ! -d "${PM2_ROOT}/stamp${builddir:+/$builddir}" ]; then
+	mkdir -p "${PM2_ROOT}/stamp${builddir:+/$builddir}"
+	if [ ! -f "${PM2_ROOT}/stamp${builddir:+/$builddir}/stamp$ext" ]; then
+	    echo $flavor > "${PM2_ROOT}/stamp${builddir:+/$builddir}/stamp$ext"
+	fi
+    fi
 }
     
 ##########################################################################
@@ -547,7 +571,7 @@ do_set() {
     STAMPDIR="${PM2_ROOT}/stamp${builddir:+/$builddir}"
     if [ -f "${STAMPDIR}/stamp$ext" ]; then
 	if [ "`cat ${STAMPDIR}/stamp$ext`" = "$flavor" ]; then
-	    echo "Modifying flavor '$flavor'"
+	    msg="Modifying flavor '$flavor'"
 	else
 	    echo 'Flavor `'"`cat ${STAMPDIR}/stamp$ext`"'` already use this repertory/extention'
 	    echo "Aborting..."
@@ -559,11 +583,12 @@ do_set() {
     elif [ -f ${PM2_CONFIG}/$flavor ]; then
 	echo "Modifying $flavor and changing repertory/extention"
 	echo "removing the old one"
-	delete_flavor || ( echo Error: aborting; exit 1 )
+	msg="Recreating flavor $flavor"
+	delete_flavor || ( echo "Error: aborting"; exit 1 )
     else
-	echo "Creating flavor $flavor"
+	msg="Creating flavor $flavor"
     fi
-    create_flavor
+    create_flavor $msg
     exit 0
 }
 
@@ -723,6 +748,29 @@ do_check() {
     exit $check_result
 }
 
+do_regenerate() {
+    file=
+    while test $# -gt 0; do
+	case "$1" in
+	--flavor=*)
+	    set_option "$1" 1 '[\-_a-zA-Z0-9]' ""
+	    file="${PM2_ROOT}/flavors/$flavor"
+	    nb_fromfile=$nb_flavor
+	    ;;	
+	*)
+	    echo Unknown option \`$1\' 1>&2
+	    usage 1
+	    ;;
+	esac
+	shift
+    done
+    for f in ${flavor:-`"$PM2_FLAVOR" list`} ; do
+	"$PM2_FLAVOR" set `"$PM2_FLAVOR" get --flavor=$f`
+    done
+
+    exit 0
+}
+
 if test $# -eq 0; then
     usage 1
 fi
@@ -732,7 +780,7 @@ ECHO=":"
 while test $# -gt 0; do
     CMD="$1"
     case "$CMD" in
-    version|set|delete|list|get|help|check)
+    version|set|delete|list|get|help|check|regenerate)
 	shift
 	$DEBUG "Executing $CMD"
 	eval do_$CMD '"$@"'
