rev 1.5 at 2000/10/17 16:21:41 GMT  .pm2conf files now go into ~/.pm2/conf//
(Logical change 1.334)


git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@3631 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/pm2/pm2/bin/pm2conf b/pm2/pm2/bin/pm2conf
--- a/pm2/pm2/bin/pm2conf
+++ b/pm2/pm2/bin/pm2conf
@@ -183,17 +183,14 @@ if [ -n "$pref_file" -a -n "$*" ] ; then
     echo "Parameters stored in file \"${PREF_DIR}/$pref_file\""
 fi
 
-PM2_CONF_DIR=`pm2-config --flavor=${PM2_FLAVOR:-default} --builddir 2>/dev/null`
-
-[ $? -eq 0 ] || error "Error: \"${PM2_FLAVOR}\" is not a valid flavor."
-
-[ -d ${PM2_CONF_DIR} ] || mkdir -p ${PM2_CONF_DIR}
-
-PM2_CONF_FILE=${PM2_CONF_DIR}/.pm2conf
+PM2_CONF_FILE=`pm2-conf-file`
+[ $? -eq 0 ] || error "Error: unable to get the .pm2conf file path."
 export PM2_CONF_FILE
 
 # Modification éventuelle de la configuration courante
 if [ $# -gt 0 ] ; then
+    PM2_CONF_DIR=`dirname ${PM2_CONF_FILE}`
+    [ -d ${PM2_CONF_DIR} ] || mkdir -p ${PM2_CONF_DIR}
     LINE=''
     while [ $# -ge 1 ]; do
 	case "$1" in
