rev 1.6 at 2000/09/12 14:55:13 GMT  Added support for generating .i files in Makefiles
(Logical change 1.312)


git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@3446 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/pm2/pm2/bin/pm2load b/pm2/pm2/bin/pm2load
--- a/pm2/pm2/bin/pm2load
+++ b/pm2/pm2/bin/pm2load
@@ -119,10 +119,14 @@ case "$1" in
 	shift
 	;;
     */*)
-	f_dir=`dirname $1`
-	f_name=`basename $1`
-	[ -x ${ex_dir}/${f_dir}/bin/${f_name} ] || error "Error: \"${ex_dir}/${f_dir}/bin/${f_name}\" exec file not found."
-	cmd_prefix="${ex_dir}/${f_dir}/bin/${f_name} "
+	if [ -f "$1" -a -x "$1" ]; then
+	    cmd_prefix="`pwd`/$1"
+        else
+	    f_dir=`dirname $1`
+	    f_name=`basename $1`
+	    [ -x ${ex_dir}/${f_dir}/bin/${f_name} ] || error "Error: \"${ex_dir}/${f_dir}/bin/${f_name}\" exec file not found."
+	    cmd_prefix="${ex_dir}/${f_dir}/bin/${f_name} "
+	fi
 	shift
 	;;
     *)
