rev 1.9 at 2000/10/30 15:52:38 GMT  pm2load has a new syntax for ambiguity resolution
(Logical change 1.340)


git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@3660 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/pm2/pm2/bin/pm2load b/pm2/pm2/bin/pm2load
--- a/pm2/pm2/bin/pm2load
+++ b/pm2/pm2/bin/pm2load
@@ -56,6 +56,19 @@ EOF
     exit $1
 }
 
+ambiguity() # prog ex_dir find_result
+{
+    echo "Error: there are multiple exec files named \"$1\" under \"$2\"."
+    echo "Please remove ambiguity by using one the following:"
+
+    for p in $3 ; do
+	rep=`echo $p | sed -e 's/.*examples\/\(.*\)\/bin.*/\1/'`
+	echo "   $PROGNAME $rep:$1 ..."
+    done
+
+    exit 1
+}
+
 PM2_FLAVOR=${PM2_FLAVOR:-default}
 export PM2_FLAVOR
 
@@ -120,15 +133,11 @@ case "$1" in
 	cmd_prefix=$1
 	shift
 	;;
-    */*)
-	if [ -f "$1" -a -x "$1" ]; then
-	    cmd_prefix="`pwd`/$1"
-        else
-	    f_dir=`dirname $1`
-	    f_name=`basename $1`
-	    [ -x ${ex_dir}/${f_dir}/bin/${f_name} ] || error "Error: \"${ex_dir}/${f_dir}/bin/${f_name}\" exec file not found."
-	    cmd_prefix="${ex_dir}/${f_dir}/bin/${f_name} "
-	fi
+    *:*)
+	f_dir=`echo $1 | cut -d: -f1`
+	f_name=`echo $1 | cut -d: -f2`
+	[ -x ${ex_dir}/${f_dir}/bin/${f_name} ] || error "Error: \"${ex_dir}/${f_dir}/bin/${f_name}\" exec file not found."
+	cmd_prefix="${ex_dir}/${f_dir}/bin/${f_name} "
 	shift
 	;;
     *)
@@ -138,7 +147,7 @@ case "$1" in
 	    files=`find ${ex_dir} -name "$1" -type f -print`
 	    [ -n "$files" ] || error "Error: no \"$1\" exec file found under \"${ex_dir}\""
 	    nb_found=`echo $files | wc -w`
-	    [ $nb_found -eq 1 ] || error "Error: there are multiple exec files named \"$1\" under \"${ex_dir}\": please remove ambiguity."
+	    [ $nb_found -eq 1 ] || ambiguity $1 ${ex_dir} "$files"
 	    cmd_prefix="`dirname $files`/$1"
         fi
 	shift
