rev 1.3 at 2000/03/02 09:45:54 GMT  Modified to search the files (in last resort) in bin/SYS/ARCH/.
(Logical change 1.86)


git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@1112 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/pm2/pm2/bin/pm2load b/pm2/pm2/bin/pm2load
--- a/pm2/pm2/bin/pm2load
+++ b/pm2/pm2/bin/pm2load
@@ -34,4 +34,30 @@
 # software is provided ``as is'' without express or implied warranty.
 #
 
-exec ${PM2_ROOT}/madeleine/bin/madload $*
+file_not_found()
+{
+    echo "$1: file not found"
+    exit 1
+}
+
+case $1 in
+    /*) command=$* ;;
+    *) if [ -f `pwd`/$1 ] ; then
+	    command=`pwd`/$*
+       else
+	    case $1 in
+		*/*) file_not_found $1 ;;
+		*) sys=`pm2_sys`
+		   arch=`pm2_arch`
+		   rep=bin/`basename $sys _SYS`/`basename $arch _ARCH`
+		   echo "Searching in $rep..."
+		   command=$rep/$*
+		   if [ ! -f $command ] ; then
+			file_not_found $1
+		   fi
+	    esac
+       fi ;;
+esac
+
+exec ${PM2_ROOT}/madeleine/bin/madload $command
+
