rev 1.4 at 2000/06/15 08:31:04 GMT  pm2load/pm2conf/pm2logs are now handled by pm2.
(Logical change 1.247)


git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@2769 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/pm2/pm2/bin/pm2logs b/pm2/pm2/bin/pm2logs
--- a/pm2/pm2/bin/pm2logs
+++ b/pm2/pm2/bin/pm2logs
@@ -34,6 +34,37 @@
 # software is provided ``as is'' without express or implied warranty.
 #
 
-. ${PM2_ROOT}/bin/pm2_vars
+PM2_FLAVOR=${PM2_FLAVOR:-default}
+export PM2_FLAVOR
 
-exec ${MAD1_ROOT}/bin/madlogs -pm2
+error() # msg
+{
+    echo $*
+    exit 1
+}
+
+# Début du script
+
+while [ $# -gt 0 ]; do
+    case $1 in
+	-f)
+	    shift; PM2_FLAVOR="$1"; shift
+	    ;;
+	*)
+	    break
+	    ;;
+    esac
+done
+
+PM2_CONF_DIR=`pm2-config --flavor=${PM2_FLAVOR:-default} --builddir 2>/dev/null`
+
+[ $? -eq 0 ] || error "Error: \"${PM2_FLAVOR}\" is not a valid flavor."
+
+PM2_CONF_FILE=${PM2_CONF_DIR}/.pm2conf
+
+[ -f ${PM2_CONF_FILE} ] || error "Error: PM2 not yet configured for flavor \"${PM2_FLAVOR}\"."
+
+for host in `cat ${PM2_CONF_FILE} | sort | uniq` ; do
+	${PM2_RSH:-rsh} $host ${PM2_ROOT}/bin/pm2_vlocallogs $host
+done
+
