do not force to use flavor mad4-mpi, use instead the flavor specified by PM2_FLAVOR
git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@14918 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/nmad/protocols/proto_mpi/scripts/mpicc b/nmad/protocols/proto_mpi/scripts/mpicc
--- a/nmad/protocols/proto_mpi/scripts/mpicc
+++ b/nmad/protocols/proto_mpi/scripts/mpicc
@@ -7,7 +7,10 @@ if [ -z "$PM2_ROOT" ] ; then
     exit 1
 fi
 
-PM2_FLAVOR=mad4-mpi
+if [ "$PM2_FLAVOR" == "" ] ; then
+    echo "Error. You need to set the variable PM2_FLAVOR to specify the pm2 flavor to use"
+    exit 1
+fi
 
 DoLink=1
 DoCompile=0
