improve error message
git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@15156 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/nmad/protocols/proto_mpi/scripts/mpirun b/nmad/protocols/proto_mpi/scripts/mpirun
--- a/nmad/protocols/proto_mpi/scripts/mpirun
+++ b/nmad/protocols/proto_mpi/scripts/mpirun
@@ -74,7 +74,7 @@ get_machines() {
 	fi
     done
     if [ "$network_name" = "Network not found" ] ; then
-	echo "$0: Cannot find a network for hosts '$host_list3', exiting..." 1>&2
+	echo "$0: Cannot find a network for protocols '$protocols' and for hosts '$host_list3' in network configuration file '$NET_FILE', exiting..." 1>&2
 	exit 1
     fi
 
