do not force the flavor to nmad-mpi
git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@18449 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/nmad/protocols/proto_mpi/scripts/mpirun b/nmad/protocols/proto_mpi/scripts/mpirun
--- a/nmad/protocols/proto_mpi/scripts/mpirun
+++ b/nmad/protocols/proto_mpi/scripts/mpirun
@@ -132,7 +132,14 @@ if [ -z "$PM2_ROOT" ] ; then
 fi
 
 if [ -z "$PM2_FLAVOR" ] ; then
-    PM2_FLAVOR=nmad-mpi
+    if [ "$1" != "-flavor" ] ; then
+	echo "Error. You need to set the variable PM2_FLAVOR to specify the pm2 flavor to use"
+	exit 1
+    else
+	shift
+	PM2_FLAVOR=$1
+	shift
+    fi
 fi
 
 dir=$(dirname $0)
