mpibenchmark:   -- catch error in case of missing benchmark in data file
git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@26860 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/mpibenchmark/mpi_bench_extract.in b/mpibenchmark/mpi_bench_extract.in
--- a/mpibenchmark/mpi_bench_extract.in
+++ b/mpibenchmark/mpi_bench_extract.in
@@ -60,19 +60,19 @@ fi
 outdir="${file}.d"
 mkdir -p ${outdir}
 
-bench_list=$( sed -e 's/# bench: \(mpi_bench_[a-zA-Z0-9_]*\) begin/\1/p;d' ${file} | sed -e 's/mpi_bench_noncontig/mpi_bench_noncontig%32/g;s/mpi_bench_rma_put_noncontig/mpi_bench_rma_put_noncontig%32/g' | tr '\n\r' ' ' )
+detected_bench_list=$( sed -e 's/# bench: \(mpi_bench_[a-zA-Z0-9_]*\) begin/\1/p;d' ${file} | sed -e 's/mpi_bench_noncontig/mpi_bench_noncontig%32/g;s/mpi_bench_rma_put_noncontig/mpi_bench_rma_put_noncontig%32/g' | tr '\n\r' ' ' )
 
 echo
 echo "# ## parsing file ${file}..."
 echo 
 echo "# ## bench list:"
-echo "# ${bench_list}"
+echo "# ${detected_bench_list}"
 echo 
 
 echo
 echo "# ## generating normalized files..."
 echo
-for b in ${bench_list}; do
+for b in ${detected_bench_list}; do
     echo "# processing bench: ${b}"
     outfile=${outdir}/${b}.dat
     echo "# This file is automatically generated from ${file} for ${b} in machine-readable format." > ${outfile}
@@ -118,12 +118,18 @@ mpi_bench_extract_sizes() {
 }
 
 if [ "x${rma}" = "x" ]; then
-    bench_list="mpi_bench_overlap_sender mpi_bench_overlap_recv mpi_bench_overlap_bidir mpi_bench_overlap_sender_noncontig mpi_bench_overlap_send_overhead mpi_bench_overlap_Nload"
+    expected_bench_list="mpi_bench_overlap_sender mpi_bench_overlap_recv mpi_bench_overlap_bidir mpi_bench_overlap_sender_noncontig mpi_bench_overlap_send_overhead mpi_bench_overlap_Nload"
 else
-    bench_list="mpi_bench_rmaoverlap_put_origin mpi_bench_rmaoverlap_put_target mpi_bench_rmaoverlap_put_passive mpi_bench_rmaoverlap_put_noncontig mpi_bench_rmaoverlap_get mpi_bench_rmaoverlap_accumulate"
+    expected_bench_list="mpi_bench_rmaoverlap_put_origin mpi_bench_rmaoverlap_put_target mpi_bench_rmaoverlap_put_passive mpi_bench_rmaoverlap_put_noncontig mpi_bench_rmaoverlap_get mpi_bench_rmaoverlap_accumulate"
 fi
 
-for b in ${bench_list}; do
+for b in ${expected_bench_list}; do
+    if [[ ! "${detected_bench_list}" =~ ${b} ]]; then
+	echo "# ## WARNING- cannot find ${b} in bench file." 1>&2
+	echo "# detected benchmarks: ${detected_bench_list}" 1>&2
+	echo
+	continue
+    fi
     case ${b} in
 	*rmaoverlap_put_passive)
 	    benchref=mpi_bench_rma_put_passive
@@ -219,6 +225,6 @@ done
 
 if [ ${out} = png ]; then
     echo "# ## generating global plot..."
-    gm convert -size 800x768 label:"${file}" $( for b in ${bench_list}; do if [ -s ${outdir}/${b}.png ]; then echo ${outdir}/${b}.png; else echo "-size 1024x768 label:${b}"; fi; done ) +append ${outdir}/all.png
+    gm convert -size 800x768 label:"${file}" $( for b in ${expected_bench_list}; do if [ -s ${outdir}/${b}.png ]; then echo ${outdir}/${b}.png; else echo "-size 1024x768 label:${b}"; fi; done ) +append ${outdir}/all.png
 fi
     
