add support for .tar.bz2 and relative paths
git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@25438 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/scripts/pm2-build-packages b/scripts/pm2-build-packages
--- a/scripts/pm2-build-packages
+++ b/scripts/pm2-build-packages
@@ -155,35 +155,88 @@ fi
 
 MAKE=make
 
+# ## extract_package_*: extracts packages from various sources, returns srcdir
+
+# find srcdir from unpacked archive
+extract_package_unpacked_archive() {
+    basedir="$1"
+    for d in ${basedir}/*; do
+	if [ -d ${d} ]; then
+	    package_srcdir=${d}
+	    break
+	fi
+    done
+    if [ ! -r ${package_srcdir} ]; then
+	echo "# ** no directory found in archive ${package}" 1>&2
+	exit 1
+    fi
+    echo "${package_srcdir}"
+}
+
+# make the given path absolute
+extract_package_make_abs() {
+    case "$1" in
+	/*)
+	    echo "$1" ;;
+	*)
+	    echo "${PWD}/$1" ;;
+    esac
+}
+
+# package is a .tar.gz
+extract_package_targz() {
+    package="`extract_package_make_abs $1`"
+    n=$( basename ${package} .tar.gz )
+    mkdir -p ${prefix}/src/${n}
+    echo "# unpacking package: ${package}" 1>&2
+    ( cd ${prefix}/src/${n} ; tar xzf ${package} )
+    extract_package_unpacked_archive "${prefix}/src/${n}"
+}
+# package is a .tar.bz2
+extract_package_tarbz2() {
+    package="`extract_package_make_abs $1`"
+    n=$( basename ${package} .tar.bz2 )
+    mkdir -p ${prefix}/src/${n}
+    echo "# unpacking package: ${package}" 1>&2
+    ( cd ${prefix}/src/${n} ; tar xjf ${package} )
+    extract_package_unpacked_archive "${prefix}/src/${n}"
+}
+
+# frontend to extract packages
+extract_package() {
+    package="$1"
+    if [ -d "${package}" ]; then
+	# package is a directory
+	echo "${package}"
+    elif [ -d "${self_path}/../${package}" ]; then
+	# package is a pm2 module name
+	echo "${self_path}/../${package}"
+    else
+	# other cases, need to extract archives to get srcdir
+	case "${package}" in
+	    *.tar.gz)
+		extract_package_targz "${package}"
+		;;
+	    *.tar.bz2)
+		extract_package_tarbz2 "${package}"
+		;;
+	    *)
+		echo "# ** cannot detect kind for package ${package}" 1>&2
+		exit 1
+		;;
+	esac
+    fi
+}
+
 build_package() {
     package="$1"
     # find package srcdir, unpack if needed
-    package_srcdir=
-    case "${package}" in
-	*.tar.gz)
-	    n=$( basename ${package} .tar.gz )
-	    mkdir -p ${prefix}/src/${n}
-	    echo "# unpacking package: ${package}"
-	    ( cd ${prefix}/src/${n} ; tar xzf ${package} )
-	    for d in ${prefix}/src/${n}/*; do
-		if [ -d ${d} ]; then
-		    package_srcdir=${d}
-		    break
-		fi
-	    done
-	    if [ ! -r ${package_srcdir} ]; then
-		echo "# ** no directory found in archive ${package}" 1>&2
-		exit 1
-	    fi
-	    echo "# package srcdir: ${package_srcdir}" 1>&2
-	    ;;
-	/*)
-	    package_srcdir="${package}"
-	    ;;
-	*)
-	    package_srcdir="${self_path}/../${package}"
-	    ;;
-    esac
+    package_srcdir="`extract_package ${package}`"
+    echo "# package srcdir: ${package_srcdir}" 1>&2
+    if [ ! -r "${package_srcdir}" ]; then
+	echo "# ** cannot read package ${package_srcdir}" 1>&2
+	exit 1
+    fi
     package_name="`basename ${package_srcdir}`"
     # build directory
     if [ "x${build_option_purge}" != "x" ]; then
@@ -193,10 +246,6 @@ build_package() {
     fi
     mkdir -p ${prefix}/build/${package_name}
     shift
-    if [ ! -r "${package_srcdir}" ]; then
-	echo "# ** cannot read package ${package}" 1>&2
-	exit 1
-    fi
     # autogen
     if [ "x${build_option_nogen}" = "x" -a -x ${package_srcdir}/autogen.sh ]; then
 	echo "# autogen: ${package_name}" 1>&2
@@ -234,7 +283,7 @@ build_package() {
     echo
     # clean-up
     if [ "x${build_option_final}" != "x" ]; then
-	echo "# delet directory ${prefix}/build/${package_name} after building" 1>&2
+	echo "# delete directory ${prefix}/build/${package_name} after building" 1>&2
 	rm -rf ${prefix}/build/${package_name}
 	echo
     fi
