create leonie flavor if needed
git-svn-id: https://scm.gforge.inria.fr/authscm/jmcoutey/svn/pm2/trunk@15658 ee107e0b-c2fa-0310-842a-ec2723fb34f4

diff --git a/mad4/bench/include/mad4_default b/mad4/bench/include/mad4_default
--- a/mad4/bench/include/mad4_default
+++ b/mad4/bench/include/mad4_default
@@ -15,8 +15,20 @@
 
 compile_leonie()
 {
-	echo "Compiling Leonie"
-	(cd ${PM2_ROOT}/leonie ; make FLAVOR=leonie)
+    echo "Compiling Leonie"
+    x=$(pm2-flavor get --flavor=leonie 2>/dev/null)
+    if [ "$x" == "" ] ; then
+        pm2-create-sample-flavors leonie
+    fi
+    LEONIE_DIR=$(pm2-config --flavor=leonie --bindir leonie 2>/dev/null)
+    if [ ! -x "$LEONIE_DIR"/leonie ] ; then
+        make FLAVOR=leonie -C $PM2_ROOT/modules/leonie | sed -e 's/^/..../'
+        LEONIE_DIR=$(pm2-config --flavor=leonie --bindir leonie 2>/dev/null)
+        if [ ! -x "$LEONIE_DIR"/leonie ] ; then
+            echo "Could not compile leonie. Aborting"
+            exit 1
+        fi
+    fi
 }
 
 # args: loop variable
